### ISSUE TITLE
[BUG] Linux sd.cpp error: mul_mat_q incompatible with CUDA arch

### ISSUE THREAD

**Issue by iwr-redmond** [NexaAI/nexa-sdk#419]
### Issue Description

Attempting to run sd.cpp inference on Linux with the CUDA build causes the following error:

```python
nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
```

### Steps to Reproduce

1. `pipx install https://github.com/NexaAI/nexa-sdk/releases/download/v0.1.1.0/nexaai-0.1.1.0-cp310-cp310-linux_aarch64.whl`
2. `nexa run sdxl-turbo:q8_0 -pf` (but any model will do)
3. Enter a positive prompt.

### OS

Ubuntu 22.04

### Python Version

3.10

### Nexa SDK Version

0.1.1.0

### GPU (if using one)

NVIDIA RTX 3060

**Comment by iwr-redmond** [comment]
Full log:

```
Model sdxl-turbo:q8_0 already exists at /nfs/corp2/nexa-sdk/hub/official/sdxl-turbo/q8_0.gguf
⠋ ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    yes
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
  |==================================================| 2641/2641 - 0.00it/s
>>> A beautiful landscape
>>> Enter your negative prompt (press Enter to skip):  (type "/exit" to quit)
⠋ /home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:2589: ERROR: CUDA kernel mul_mat_q has no device code compatible with CUDA arch 520. ggml-cuda.cu was compiled for: 520
ggml_cuda_compute_forward: CONT failed
CUDA error: unspecified launch failure
  current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2174
  err
/home/runner/work/nexa-sdk/nexa-sdk/dependency/stable-diffusion.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:70: CUDA error
⠙ Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
Aborted (core dumped)
```

**Comment by iwr-redmond** [comment]
Fix available upstream in [stable-diffusion.cpp#541](https://github.com/leejet/stable-diffusion.cpp/issues/541)

**Comment by MaokunZhang** [comment]
👋 Important Update: Nexa-SDK was fully rewritten on July 23, 2025, paving the way for exciting new features. This issue relates to a legacy version (v1) and has now been archived with the label legacy.

👉 Still experiencing this issue in the new version? Please open a new issue
🔗 Explore what's new in Nexa-SDK v2: [README](https://github.com/NexaAI/nexa-sdk)

Thanks for helping us make Nexa-SDK even better! 🚀✨
